name: 'ACCELQ Github-A Connect'
description: 'Execute ACCELQ registered CI Jobs from Github Actions'

inputs:
  appURL:
    description: 'Your ACCELQ Application URL in the exact following format: https://<hostname>:<port_num>'
    required: true
  userName:
    description: 'Your ACCELQ User ID'
    required: true
  apiKey:
    description: 'API key available in Profile section of ACCELQ'
    required: true
  tenantCode:
    description: 'Tenant Code displayed in the Profile section of ACCELQ'
    required: true
  jobId:
    description: 'This ID should come from the CI job you saved in ACCELQ application'
    required: true
  runParam:
    description: "Run Params(optional) should be JSON string form example: '{\"username\": \"John Todd\", \"password\": \"bxW&=UVw\"}'"
    required: false
  proxyHost:
    description: 'Proxy Host (optional)'
    required: false
  proxyPort:
    description: 'Proxy Port (optional)'
    required: false
  stepFailureThreshold:
    description: "Percentage ACCELQ test case failure (Optional), beyond which this Step in the Pipeline will be marked as a failure. If this is zero, even a single failed test will cause the Step to fail. If you never want to fail the Pipeline Step due to failing Automation tests, input -1. Input a valid integer between 0 and 100 or, -1."
    required: false
  maxWaitTimeInMins:
    description: "Maximum time to wait for the job to be picked up by an ACCELQ Agent. Default is 15 mins."
    required: false
  waitForJobCompletion:
    description: 'If true, wait for the job to be completed. If false, run the job and exit. Default is true.'
    required: false
outputs:
  result-url:
    description: "The ACCELQ url to access the job results"
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'award'  
  color: 'blue'
